# Header
menu:
  主页: /
  归档: /archives
  日志: /log

rss: /atom.xml

home:
  style: default           # default, detail

favicon: /someimg/icon.jpg         # Path to the custom favicon (e.g. "/favicon.png" if your favicon file is located at /source/favicon.png)

# Banner
banner:
  enable: true            # Display banner
  url: /someimg/bg11.jpg
  position: center         # Specifies the alignment of the image, see the "object-position" property in CSS
  onAllPages: true         # Display banner on all pages

# Appearence
hue: 260                   # The hue of the theme color (e.g. red: 0, orange: 60, blue: 260, purple: 300, pink: 345)

# Sidebar
sidebar:
  widgets:                 # Plugins to be enabled (profile, category, tag, archive, recent_posts)
    normal:                # Scroll along with the page
      - profile
    sticky:                # Stick to the top of the page
      - category
      - tag
      - archive
      - recent_posts

# Widget behavior
archive_type: 'monthly'
recent_posts_limits: 5

# Personal info
avatar: /someimg/piccc.png
author: QBrer
subtitle: 简单记录下我所想
links:
  - name: QQ 3093815036
    icon: fa-brands fa-qq      # Find icon codes at https://fontawesome.com/search
    # url: https://space.bilibili.com/424753682?spm_id_from=333.1007.0.0
		url: https://im.qq.com/index/
  - name: 邮箱 15137869764@163.com
    icon: fa-solid fa-envelope
    # url: https://steamcommunity.com/id/aiaodfioaio/
		url: https://mail.163.com/
  - name: GitHub
    icon: fa-brands fa-github
    url: https://github.com/QBrer

comment:
  valine:
    enable: ture
    enableQQ: false
    enableOS: false
    appId: XiigNuiC5qAEMsvXgA4CZRdS-MdYXbMMI
    appKey: onmZNb4nJ2EpQ4jTIGroP5t5
    placeholder: 暂未配置邮件提醒，不能及时回复还请见谅😥
    pageSize: 10
    highlight: true
    serverURLs: https://api.b.qbrer.me
    emojiCDN: 'https://cdn.jsdelivr.net/gh/QBrer/Tieba-lulu-emoji/'
    emojiMaps: {
	"Tieba1": "Tieba/1f44d.png",
	"Tieba2": "Tieba/1f603.png",
	"Tieba3": "Tieba/1f605.png",
	"Tieba4": "Tieba/1f606.png",
	"Tieba5": "Tieba/1f608.png",
	"Tieba6": "Tieba/1f609.png",
	"Tieba7": "Tieba/1f60b.png",
	"Tieba8": "Tieba/1f60d.png",
	"Tieba9": "Tieba/1f60e.png",
	"Tieba10": "Tieba/1f60f.png",
	"Tieba11": "Tieba/1f610.png",
	"Tieba12": "Tieba/1f612.png",
	"Tieba13": "Tieba/1f613.png",
	"Tieba14": "Tieba/1f615.png",
	"Tieba15": "Tieba/1f621.png",
	"Tieba16": "Tieba/1f626.png",
	"Tieba17": "Tieba/1f62d.png",
	"Tieba18": "Tieba/1f630.png",
	"Tieba19": "Tieba/1f633.png",
	"Tieba20": "Tieba/1f634.png",
	"Tieba21": "Tieba/1f642.png",
	"Tieba22": "Tieba/1f911.png",
	"Tieba23": "Tieba/1f923.png",
	"Tieba24": "Tieba/1f928.png",
	"Tieba25": "Tieba/1f92c.png",
	"Tieba26": "Tieba/1f92e.png",
	"Tieba27": "Tieba/1f97a.png",
	"Tieba28": "Tieba/2639.png",
	"Tieba29": "Tieba/263a.png",    	
	"lulu1": "lulu/45aafb6134a85edf3bffc8f40c540923dc547517.png",
	"lulu2": "lulu/75cf33eff01f3a2982bbe319dc25bc315d607c17.png",
	"lulu3": "lulu/a1ilj-u86wo.png",
	"lulu4": "lulu/a10ua-1ya8i.gif",
	"lulu5": "lulu/a3fpb-23in1.gif",
	"lulu6": "lulu/a3t3r-bki8d.gif",
	"lulu7": "lulu/a6co8-kghbl.gif",
	"lulu8": "lulu/ac51e-a5f2y.gif",
	"lulu9": "lulu/acq6j-w9acj.gif",
	"lulu10": "lulu/acr5g-11jw4.gif",
	"lulu11": "lulu/afu1m-0wtx4.gif",
	"lulu12": "lulu/ag7iu-yi5n7.gif",
	"lulu13": "lulu/aj9x9-bhe9q.gif",
	"lulu14": "lulu/aktlz-gm54k.gif",
	"lulu15": "lulu/an73b-m5ccp.gif",
	"lulu16": "lulu/ao24h-kk66i.gif",
	"lulu17": "lulu/aoses-mupbp.gif",
	"lulu18": "lulu/atbwe-m11gc.gif",
	"lulu19": "lulu/aw6oc-b1gkv.gif",
	"lulu20": "lulu/aygix-uxuc9.gif",
    } 
     
    # Other supported parameters can be added here if needed
    # Visit https://valine.js.org/configuration.html for more details
